### ISSUE TITLE
modpack issue

### ISSUE THREAD

**Issue by RaitoSuguiyama** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#115]
## Base information
* Minecraft version: 1.12.2-20.0.53
* Minecraft Forge version: 1.6.3
* TolkienCraft III version: TolkienCraft III-1.12.2-2.0.53.zip

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Without a crash report or error log there is nothing I can do.  It is possible that the version of java could be a problem, but that is simply a guess without errors.

**Comment by CaptainD54321** [comment]
I'm having the same issue, none of the 1.12 versions of the pack on curseforge will install; if I try to manually download and import them into the FTB app it just says the .zip file isn't a valid pack. The old 1.10 version of the pack **does** work however

**Comment by GreatOrator** [comment]
Again, same thing, without a crash report or error log there is nothing I can do. It is possible that the version of java could be a problem, but that is simply a guess without errors.

**Comment by CaptainD54321** [comment]
I don't think you're understanding the issue properly, there is no Minecraft crash report or error log, nor is the java version possibly an issue, because the modpack won't even _**install**_. 

When attempting to install the pack from the FTB app it displays this error on screen:
![Image](https://github.com/user-attachments/assets/89f1eaf1-778e-4fdd-97ba-aaae8fa8ea29)
And outputs this error to stdout:
```
[23:48:16] [Long Running Executor 0/INFO] [dev.ftb.app.install.tasks.DownloadTask]:   Downloading url: https://edge.forgecdn.net/files/2857/223/TolkienCraft%20III-1.12.2-2.0.53.zip
23:48:51.184 › [23:48:51][D][ftb-app::background.ts] Subprocess stdout [23:48:51] [Long Running Executor 0/INFO] [dev.ftb.app.install.tasks.DownloadTask]:   File downloaded.
23:48:51.185 › [23:48:51][D][ftb-app::background.ts] Subprocess stdout [23:48:51] [Long Running Executor 0/INFO] [dev.ftb.app.install.InstanceInstaller]: Extracting CurseForge overrides.
23:48:51.196 › [23:48:51][D][ftb-app::background.ts] Subprocess stdout [23:48:51] [Long Running Executor 0/ERROR] [dev.ftb.app.task.InstallationOperation]: Fatal exception whilst installing modpack.
dev.ftb.app.install.InstanceInstaller$InstallationFailureException: Failed to install.
	at dev.ftb.app.install.InstanceInstaller.execute(InstanceInstaller.java:310) ~[app-1.27.3-all.jar:?]
	at dev.ftb.app.task.InstallationOperation.doOperation(InstallationOperation.java:46) ~[app-1.27.3-all.jar:?]
	at dev.ftb.app.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:71) ~[app-1.27.3-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[app-1.27.3-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at jdk.nio.zipfs.ZipFileSystem.checkUTF8(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source) ~[jdk.zipfs:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at net.covers1624.quack.io.IOUtils.getFileSystem(IOUtils.java:250) ~[app-1.27.3-all.jar:?]
	at net.covers1624.quack.io.IOUtils.getJarFileSystem(IOUtils.java:217) ~[app-1.27.3-all.jar:?]
	at net.covers1624.quack.io.IOUtils.getJarFileSystem(IOUtils.java:195) ~[app-1.27.3-all.jar:?]
	at dev.ftb.app.install.InstanceInstaller.execute(InstanceInstaller.java:280) ~[app-1.27.3-all.jar:?]
	... 7 more
```


When attempting to install the pack by importing the .zip downloaded from CurseForge, it just gives this on-screen:
![Image](https://github.com/user-attachments/assets/4b8bec0a-99ec-42a7-961b-7238e9fd5b54)
With no console log at all.

It seems like there's something wrong with the format of the .zip thats on curseforge, which means the FTB app isn't recognizing it properly, but I don't know enough about how its supposed to be formatted to have any idea what that problem could be

**Comment by GreatOrator** [comment]
That's still more to go by than the earlier post.

Based on that, I would start with curseforge support.  The zip was working for years through them before, so if it stopped, something had to have changed on their end.  or something with FTB (I honestly do not know).

The primary issue with the modpack being re-uploaded is it was using older methods and some of the mods in the pack are no longer available for download publicly (some of the mods are not available on curse and have to be downloaded remotely and added in to the zip to upload) so I wouldn't be able to.
