### ISSUE TITLE
Crash at map install button, can't find map download

### ISSUE THREAD

**Issue by Rah-zin** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#116]
## Description
Downloaded the modpack through Curseforge. Works fine, loads fine, but at the main menu, when I click the button to download the map, it hangs, then crashes. Did some digging around in the forums and found the link that it should be opening, but that goes nowhere and shows a DNS error. Saw some posts saying that it must be downloaded through MediaFire, but did not see an actual MediaFire link anywhere. Did manage to find and download the world file under the github project Tolkiencraft-3-Map, however when I either copy that world file into the saves folder, or create a randomly generated save and then dump the contents of the map download into that folder, I spawn in an empty overworld and fall into the void, even when respawning. Seems like not quite the right map.

Crash report below from the initial crash when clicking the button to install the map ingame.

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 14.23.5.2847
* TolkienCraft III version: 2.0.53 

## Crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  iceandfire (iceandfire-1.8.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 4/24/24 12:47 PM
Description: Updating screen events

java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.brandon3055.madhelp.handlers.ContentHandler.readContentFile(ContentHandler.java:283)
	at com.brandon3055.madhelp.handlers.ContentHandler.reloadContentList(ContentHandler.java:62)
	at com.brandon3055.madhelp.handlers.ForgeEventHandler.buttonPressed(ForgeEventHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1187_ForgeEventHandler_buttonPressed_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at lumien.custommainmenu.gui.GuiCustom.func_146284_a(GuiCustom.java:701)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at lumien.custommainmenu.gui.GuiCustom.func_73864_a(GuiCustom.java:245)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.brandon3055.madhelp.handlers.ContentHandler.readContentFile(ContentHandler.java:283)
	at com.brandon3055.madhelp.handlers.ContentHandler.reloadContentList(ContentHandler.java:62)
	at com.brandon3055.madhelp.handlers.ForgeEventHandler.buttonPressed(ForgeEventHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1187_ForgeEventHandler_buttonPressed_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at lumien.custommainmenu.gui.GuiCustom.func_146284_a(GuiCustom.java:701)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at lumien.custommainmenu.gui.GuiCustom.func_73864_a(GuiCustom.java:245)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.brandon3055.madhelp.client.GuiDownloadList
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1414571448 bytes (1349 MB) / 3732406272 bytes (3559 MB) up to 5756682240 bytes (5490 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6176m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                   | Source                                                    | Signature                                |
	|:------ |:----------------------- |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                    | minecraft.jar                                             | None                                     |
	| LCHIJA | mcp                     | 9.42                      | minecraft.jar                                             | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                 | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
	| LCHIJA | forge                   | 14.23.5.2847              | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
	| LCHIJA | foamfixcore             | 7.7.4                     | minecraft.jar                                             | None                                     |
	| LCHIJA | akashictome             | 1.2-12                    | AkashicTome-1.2-12.jar                                    | None                                     |
	| LCHIJA | allomancy               | 2.9.1                     | allomancy-2.9.1.jar                                       | None                                     |
	| LCHIJA | antiqueatlas            | 4.6.3                     | antiqueatlas-1.12.2-4.6.3.jar                             | None                                     |
	| LCHIJA | antiqueatlasoverlay     | 1.2                       | antiqueatlas-1.12.2-4.6.3.jar                             | None                                     |
	| LCHIJA | architecturecraft       | @VERSION@                 | architecturecraft-1.12-3.98.jar                           | None                                     |
	| LCHIJA | aroma1997core           | 2.0.0.2.b165              | Aroma1997Core-1.12.2-2.0.0.2.b165.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | baubles                 | 1.5.2                     | Baubles-1.12-1.5.2.jar                                    | None                                     |
	| LCHIJA | astralsorcery           | 1.10.20                   | astralsorcery-1.12.2-1.10.20.jar                          | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | atlcraft                | MC1.12-Ver1.9             | ATLCraftCandlesMod(MC1.12-Ver1.9).jar                     | None                                     |
	| LCHIJA | morphtool               | 1.2-21                    | Morph-o-Tool-1.2-21.jar                                   | None                                     |
	| LCHIJA | jei                     | 4.15.0.293                | jei_1.12.2-4.15.0.293.jar                                 | None                                     |
	| LCHIJA | quark                   | r1.6-177                  | Quark-r1.6-177.jar                                        | None                                     |
	| LCHIJA | autoreglib              | 1.3-32                    | AutoRegLib-1.3-32.jar                                     | None                                     |
	| LCHIJA | betteradvancements      | 0.1.0.77                  | BetterAdvancements-1.12.2-0.1.0.77.jar                    | None                                     |
	| LCHIJA | betteragriculture       | 1.2.3                     | betteragriculture-1.12.2-1.2.3.jar                        | None                                     |
	| LCHIJA | betterquesting          | 3.5.300                   | BetterQuesting-3.5.300.jar                                | None                                     |
	| LCHIJA | bqt                     | 1.0                       | BetterQuestingTriggerer-1.0.jar                           | None                                     |
	| LCHIJA | bibliocraft             | 2.4.5                     | BiblioCraft[v2.4.5][MC1.12.2].jar                         | None                                     |
	| LCHIJA | birdsnests              | 2.1.0                     | BirdsNests1.12.2-2.1.0.jar                                | None                                     |
	| LCHIJA | waila                   | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                               | None                                     |
	| LCHIJA | modularrouters          | 1.12.2-3.2.2              | modular-routers-1.12.2-3.2.2.jar                          | None                                     |
	| LCHIJA | guideapi                | 1.12-2.1.8-63             | Guide-API-1.12-2.1.8-63.jar                               | None                                     |
	| LCHIJA | bloodmagic              | 1.12.2-2.4.3-105          | BloodMagic-1.12.2-2.4.3-105.jar                           | None                                     |
	| LCHIJA | bqmie                   | 2.0.1                     | BQMIE-1.12.2-2.0.1.0-universal.jar                        | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux            | 2.1.0                     | RedstoneFlux-1.12-2.1.0.6-universal.jar                   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | brandonscore            | 2.4.17                    | BrandonsCore-1.12.2-2.4.17.208-universal.jar              | None                                     |
	| LCHIJA | chameleon               | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                                  | None                                     |
	| LCHIJA | chickenchunks           | 2.4.2.74                  | ChickenChunks-1.12.2-2.4.2.74-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ctm                     | MC1.12.2-1.0.1.30         | CTM-MC1.12.2-1.0.1.30.jar                                 | None                                     |
	| LCHIJA | roots                   | 1.12.2-3.0.21             | Roots-1.12.2-3.0.21.jar                                   | None                                     |
	| LCHIJA | mysticalworld           | 1.12.2-1.6.1              | mysticalworld-1.12.2-1.6.1.jar                            | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-1.0.1.44         | Chisel-MC1.12.2-1.0.1.44.jar                              | None                                     |
	| LCHIJA | chiselsandbits          | 14.33                     | chiselsandbits-14.33.jar                                  | None                                     |
	| LCHIJA | cofhcore                | 4.6.3                     | CoFHCore-1.12.2-4.6.3.27-universal.jar                    | None                                     |
	| LCHIJA | cofhworld               | 1.3.1                     | CoFHWorld-1.12.2-1.3.1.7-universal.jar                    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | craftingtweaks          | 8.1.9                     | CraftingTweaks_1.12.2-8.1.9.jar                           | None                                     |
	| LCHIJA | custommainmenu          | 2.0.9                     | CustomMainMenu-MC1.12.2-2.0.9.jar                         | None                                     |
	| LCHIJA | customnpcs              | 1.12                      | CustomNPCs_1.12.2-(01Oct19).jar                           | None                                     |
	| LCHIJA | customstartinggear      | 1.2.0                     | CustomStartingGear-1.12-1.2.0.9-universal.jar             | None                                     |
	| LCHIJA | ptrmodellib             | 1.0.4                     | PTRLib-1.0.4.jar                                          | None                                     |
	| LCHIJA | props                   | 2.6.3                     | Decocraft-2.6.3_1.12.2.jar                                | None                                     |
	| LCHIJA | forestry                | 5.8.2.409                 | forestry_1.12.2-5.8.2.409.jar                             | None                                     |
	| LCHIJA | eleccore                | 1.9.452                   | ElecCore-1.12.2-1.9.452.jar                               | None                                     |
	| LCHIJA | mcjtylib_ng             | 3.5.4                     | mcjtylib-1.12-3.5.4.jar                                   | None                                     |
	| LCHIJA | deepresonance           | 1.8.0                     | deepresonance-1.12-1.8.0.jar                              | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.5.6              | journeymap-1.12.2-5.5.6.jar                               | None                                     |
	| LCHIJA | defaultoptions          | 9.2.8                     | DefaultOptions_1.12.2-9.2.8.jar                           | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.3                     | ThermalFoundation-1.12.2-2.6.3.27-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | draconicevolution       | 2.3.24                    | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar        | None                                     |
	| LCHIJA | uteamcore               | 2.2.4.133                 | u_team_core-1.12.2-2.2.4.133.jar                          | None                                     |
	| LCHIJA | drawbridge              | 1.2.1.8                   | draw_bridge-1.12.2-1.2.1.8.jar                            | None                                     |
	| LCHIJA | embers                  | 0.230                     | embers-0.230.jar                                          | None                                     |
	| LCHIJA | enderstorage            | 2.4.6.137                 | EnderStorage-1.12.2-2.4.6.137-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | mantle                  | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
	| LCHIJA | tconstruct              | 1.12.2-2.13.0.171         | TConstruct-1.12.2-2.13.0.171.jar                          | None                                     |
	| LCHIJA | extrautils2             | 1.0                       | extrautils2-1.12-1.9.9.jar                                | None                                     |
	| LCHIJA | ezstorage               | 2.5.0                     | ezstorage-2.5.0-[1.12.2].jar                              | None                                     |
	| LCHIJA | fastleafdecay           | v14                       | FastLeafDecay-v14.jar                                     | None                                     |
	| LCHIJA | flatcoloredblocks       | mc1.12-6.8                | flatcoloredblocks-mc1.12-6.8.jar                          | None                                     |
	| LCHIJA | foamfix                 | 0.10.10-1.12.2            | foamfix-0.10.10-1.12.2.jar                                | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar              | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar              | None                                     |
	| LCHIJA | llibrary                | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire              | 1.8.3                     | iceandfire-1.8.3.jar                                      | None                                     |
	| LCHIJA | improvedbackpacks       | 1.12.2-1.4.0.0            | ImprovedBackpacks-1.12.2-1.4.0.0.jar                      | None                                     |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                           | None                                     |
	| LCHIJA | jaff                    | 1.7_for_1.12              | JustAFewFish-1.7_for_1.12.jar                             | None                                     |
	| LCHIJA | justenoughdimensions    | 1.6.0-dev.20191019.172643 | justenoughdimensions-1.12.2-1.6.0-dev.20191019.172643.jar | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCHIJA | jeresources             | 0.9.2.60                  | JustEnoughResources-1.12.2-0.9.2.60.jar                   | None                                     |
	| LCHIJA | keywizard               | 1.12.2-1.7.3              | keywizard-1.12.2-1.7.3.jar                                | None                                     |
	| LCHIJA | levelup2                | ${version}                | Level Up! 2-1.1.23-1.12.jar                               | None                                     |
	| LCHIJA | llor                    | 1.1.6-mc1.12.2            | LLOverlayReloaded-1.1.6-mc1.12.2.jar                      | None                                     |
	| LCHIJA | lootbags                | 2.5.8.5                   | LootBags-1.12.2-2.5.8.5.jar                               | None                                     |
	| LCHIJA | madhelp                 | 3.0.0                     | MadHelp-1.12.2-3.0.0-universal.jar                        | None                                     |
	| LCHIJA | mca                     | 6.1.0                     | MCA-1.12.2-6.1.0-universal.jar                            | None                                     |
	| LCHIJA | monk                    | 1.4                       | monk-mod-1.4.jar                                          | None                                     |
	| LCHIJA | morpheus                | 1.12.2-3.5.106            | Morpheus-1.12.2-3.5.106.jar                               | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.4.43                  | MrTJPCore-1.12.2-2.1.4.43-universal.jar                   | None                                     |
	| LCHIJA | bq_npc_integration      | 3.4.32                    | NPCIntegration-3.4.32.jar                                 | None                                     |
	| LCHIJA | oreexcavation           | 1.4.143                   | OreExcavation-1.4.143.jar                                 | None                                     |
	| LCHIJA | harvestcraft            | 1.12.2zb                  | Pam's HarvestCraft 1.12.2zf.jar                           | None                                     |
	| LCHIJA | patchouli               | 1.0-20                    | Patchouli-1.0-20.jar                                      | None                                     |
	| LCHIJA | perfectspawn            | 2.1                       | PerfectSpawn-MC1.12.2-2.1.jar                             | None                                     |
	| LCHIJA | subcommonlib            | 1.2.0.1                   | subcommonlib-sublib-1.12.2-1.2.0.4.jar                    | None                                     |
	| LCHIJA | petbuddy                | $version                  | petbuddy-petbuddy-1.12.2-2.4.1.0.jar                      | None                                     |
	| LCHIJA | projectred-core         | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-Base.jar                      | None                                     |
	| LCHIJA | projectred-integration  | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-integration.jar               | None                                     |
	| LCHIJA | projectred-transmission | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-integration.jar               | None                                     |
	| LCHIJA | railcraft               | 12.0.0                    | railcraft-12.0.0.jar                                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | xreliquary              | 1.12.2-1.3.4.796          | Reliquary-1.12.2-1.3.4.796.jar                            | None                                     |
	| LCHIJA | resourceloader          | 1.5.3                     | ResourceLoader-MC1.12.1-1.5.3.jar                         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | corerm                  | 1.3.3                     | RikMuldsCore_1.3.3.jar                                    | None                                     |
	| LCHIJA | bq_standard             | 3.4.159                   | StandardExpansion-3.4.159.jar                             | None                                     |
	| LCHIJA | storagedrawers          | 1.12.2-5.4.0              | StorageDrawers-1.12.2-5.4.0.jar                           | None                                     |
	| LCHIJA | camping                 | 2.4.3                     | TheCampingMod_2.4.3.jar                                   | None                                     |
	| LCHIJA | tinkertoolleveling      | 1.12.2-1.1.0.DEV.b23e769  | TinkerToolLeveling-1.12.2-1.1.0.jar                       | None                                     |
	| LCHIJA | tolkienmobs             | 1.12.30.37                | TolkienMobs-1.12.2-1.12.30.37.0-universal.jar             | None                                     |
	| LCHIJA | tolkientweaks           | 3.0.7.23                  | TolkienTweaks-1.12.2-3.0.7.23.38-universal.jar            | None                                     |
	| LCHIJA | torchmaster             | 1.8.1.81                  | torchmaster_1.12.2-1.8.1.81.jar                           | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | torchoptimizer          | 1.12.2-2.2.6              | torchoptimizer-1.12.2-2.2.6.jar                           | None                                     |
	| LCHIJA | townbuilder             | 3.0.0                     | TownBuilder-1.12.2-3.0.0-universal.jar                    | None                                     |
	| LCHIJA | translocators           | 2.5.2.81                  | Translocators-1.12.2-2.5.2.81-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | variedcommodities       | 1.12.2                    | VariedCommodities_1.12.2(21nov19).jar                     | None                                     |
	| LCHIJA | wawla                   | 2.5.273                   | Wawla-1.12.2-2.5.273.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wolfarmor               | 3.3.0.279                 | wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar               | None                                     |
	| LCHIJA | woot                    | 1.12.2-1.4.11             | woot-1.12.2-1.4.11.jar                                    | None                                     |
	| LCHIJA | worldedit               | 6.1.10-SNAPSHOT           | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar         | None                                     |
	| LCHIJA | immersiveengineering    | 0.12-92                   | ImmersiveEngineering-0.12-92.jar                          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | eleccoreloader          | 1.9.452                   | ElecCore-1.12.2-1.9.452.jar                               | None                                     |
	| LCHIJA | mysticallib             | 1.12.2-1.4.0              | mysticallib-1.12.2-1.4.0.jar                              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
  lumien.perfectspawn.asm.ClassTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
iceandfire (iceandfire-1.8.3.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
WolfArmorCore (wolfarmor-1.12.2-3.3.0.279-SNAPSHOT-all.jar)
  
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.101.1371' Renderer: 'Intel(R) UHD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Launched Version: forge-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 30.0.101.1371, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
```

**Comment by GreatOrator** [comment]
https://www.mediafire.com/file/4u3nq40anycxabx/MiddleEarth-DefaultTC3_1_12_2.zip/file

tried to send that to you on curse, but there is the direct link to download.  Stupid curseforge

**Comment by Rah-zin** [comment]
> https://www.mediafire.com/file/4u3nq40anycxabx/MiddleEarth-DefaultTC3_1_12_2.zip/file
> 
> tried to send that to you on curse, but there is the direct link to download. Stupid curseforge

Amazing, thank you! Did not expect such a quick response. Also, for what it's worth, I cannot give you enough props for how amazing these packs have been, and your map in particular.
