### ISSUE TITLE
Server crash when installing

### ISSUE THREAD

**Issue by mrsaminus** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#35]
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-1.10.2-12.18.3.2281-universal
* TolkienCraft III version: Update v0.11.6-beta part Deux

## Crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.7.102-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  llibrary (llibrary-1.7.6-1.10.2.jar)
  CorePlugin (MrTJPCore-1.10.2-2.0.0.17-universal.jar)
  PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 6/10/17 4:42 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: betterquesting/client/gui/GuiQuestLinesMain
	at betterquesting.handlers.EventHandler.onWorldLoad(EventHandler.java:266)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_134_EventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: betterquesting.client.gui.GuiQuestLinesMain
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4409e975 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more
Caused by: java.lang.RuntimeException: Attempted to load class betterquesting/client/gui/GuiQuestLinesMain for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.16.0-0.bpo.4-amd64
	Java Version: 1.8.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1275361224 bytes (1216 MB) / 2559954944 bytes (2441 MB) up to 18407424000 bytes (17554 MB)
	JVM Flags: 22 total; -Xms512M -XX:PermSize=384M -XX:MaxPermSize=768M -XX:-UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=2
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAA	allomancy{2.2.1} [Allomancy] (allomancy-2.2.1.jar) 
	UCHIJAA	antiqueatlas{4.4.3} [Antique Atlas] (antiqueatlas-1.9.4-4.4.3.jar) 
	UCHIJAA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAA	atlcraft{1.10.2-Ver1.5} [ATLCraft Candles Mod] (ATLCraftCandlesMod(MC1.10.2-Ver1.5).jar) 
	UCHIJAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJAA	betteragriculture{1.0.1} [Better Agriculture] (BetterAgriculture-[1.10.2]-1.0.1.jar) 
	UCHIJAA	betterquesting{2.3.228} [Better Questing] (BetterQuesting-2.3.228.jar) 
	UCHIJAA	bqt{0.9} [Better Questing Triggerer] (BetterQuestingTriggerer-0.9.jar) 
	UCHIJAA	BiblioCraft{2.2.3} [BiblioCraft] (BiblioCraft[v2.2.3][MC1.10.2].jar) 
	UCHIJAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAA	BloodMagic{1.10.2-2.1.10-79} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.10-79.jar) 
	UCHIJAA	bqmie{1.0.0} [BQMIE] (BQMIE-1.10.2-1.0.0.1-universal.jar) 
	UCHIJAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	UCHIJAA	brandonscore{9.9.9} [Brandon's Core] (BrandonsCore-1.10.2-2.1.7.102-universal.jar) 
	UCHIJAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	UCHIJAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJAA	crashlogadditions{1.1} [Crash Log Additions] (CrashLogAdditions-1.10.2-1.1.jar) 
	UCHIJAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(25may17).jar) 
	UCHIJAA	customstartinggear{1.0.0} [Custom Starting Gear] (CustomStartingGear-1.10.2-1.0.0.7-universal.jar) 
	UCHIJAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJAA	forestry{5.2.17.376} [Forestry] (forestry_1.10.2-5.2.17.376.jar) 
	UCHIJAA	eleccore{1.7.421} [ElecCore] (ElecCore-1.10.2-1.7.421.jar) 
	UCHIJAA	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.1x-1.4.8.jar) 
	UCHIJAA	draconicevolution{2.0.12} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.12.222-universal.jar) 
	UCHIJAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCHIJAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.3.jar) 
	UCHIJAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAA	forgemultipartcbe{2.0.0.31} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAA	microblockcbe{2.0.0.31} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAA	minecraftmultipartcbe{2.0.0.31} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAA	Waila{1.8.13-B27_1.10.2} [Waila] (Hwyla-1.8.13-B27_1.10.2.jar) 
	UCHIJAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.10.2.jar) 
	UCHIJAA	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UCHIJAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAA	immersiveengineering{0.10-58} [Immersive Engineering] (ImmersiveEngineering-0.10-58.jar) 
	UCHIJAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAA	justenoughdimensions{1.5.0} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.5.0.jar) 
	UCHIJAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.9-1.10.2.jar) 
	UCHIJAA	lootbags{2.3.9} [Loot Bags] (LootBags-1.10.2-2.3.9.jar) 
	UCHIJAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAA	modularrouters{1.10.2-1.3.1} [Modular Routers] (modular-routers-1.10.2-1.3.1.jar) 
	UCHIJAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAA	MrTJPCoreMod{2.0.0.17} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.17-universal.jar) 
	UCHIJAA	bq_npc_integration{CI_MOD_VERSION} [NPC Integration] (NPCIntegration-2.3.22.jar) 
	UCHIJAA	oreexcavation{1.2.93} [OreExcavation] (OreExcavation-1.2.93.jar) 
	UCHIJAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAA	PerfectSpawn{1.4} [Perfect Spawn] (PerfectSpawn-MC1.10.2-1.4.jar) 
	UCHIJAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAA	petbuddy{1.11 2.3.1.7 backport for 1.10} [Pet Buddy] (petbuddy-1.10.2-2.3.1.9 .jar) 
	UCHIJAA	projectred-core{4.8.2.41} [ProjectRed Core] (ProjectRed-1.10.2-4.8.2.41-Base.jar) 
	UCHIJAA	projectred-integration{4.8.2.41} [ProjectRed integration] (ProjectRed-1.10.2-4.8.2.41-integration.jar) 
	UCHIJAA	projectred-transmission{4.8.2.41} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.2.41-integration.jar) 
	UCHIJAA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
	UCHIJAA	xreliquary{1.10.2-1.3.3.664} [Reliquary] (Reliquary-1.10.2-1.3.3.664.jar) 
	UCHIJAA	corerm{1.2e-1.9.4} [RikMuld's Core] (RikMuldsCore_1.2e-1.10.2.jar) 
	UCHIJAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAA	bq_standard{2.3.131} [Standard Expansion] (StandardExpansion-2.3.131.jar) 
	UCHIJAA	StorageDrawers{1.10.2-3.7.8} [Storage Drawers] (StorageDrawers-1.10.2-3.7.8.jar) 
	UCHIJAA	camping{2.3d-1.9.4} [The Camping Mod 2] (TheCampingMod_2.3d-1.10.2.jar) 
	UCHIJAA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	UCHIJAA	thut_wearables{1.1.2} [Thut's Wearables] (thut_wearables-1.1.2.jar) 
	UCHIJAA	thutcore{3.12.2} [ThutCore] (thutcore-3.12.2.jar) 
	UCHIJAA	thut_bling{1.0.1} [Thut's Bling] (thut_bling-1.0.1.jar) 
	UCHIJAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAA	tolkientweaks{2.0.2} [Tolkien Tweaks] (TolkienTweaks-1.10.2-2.0.2.21-universal.jar) 
	UCHIJAA	TownBuilder{1.0.0-Build8} [Town Builder] (TownBuilder-1.10.2-2.0.0.1-universal.jar) 
	UCHIJAA	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	UCHIJAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.4.1.0.jar) 
	UCHIJAA	Woot{1.10.2-1.4.0} [Woot] (woot-1.10.2-1.4.0.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.7.102-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
llibrary (llibrary-1.7.6-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (MrTJPCore-1.10.2-2.0.0.17-universal.jar)
  
PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
  lumien.perfectspawn.asm.PSClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	TolkienCraft III - Return to Middle-earth - 0.9.4: 
			30 years have passed
			and things are not well.

	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 1000; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by GreatOrator** [comment]
Yup, was already aware and funwayguy has fixed it, though unfortunately I seemed to miss the file in the server package on curse.  Just remove better questing version 228 and replace with version 225.  There will be a new update to fix that and a few other bugs next week.
