### ISSUE TITLE
Map download fails

### ISSUE THREAD

**Issue by bradleypuckett** [GreatOrator/TolkienCraft-3-Return-to-Middle-earth#82]
## Description
Map download fails with Connection refused. Attempting to download in-browser from http://repository.a2g.gs/modpacks/tolkiencraft/3/MiddleEarth-DefaultTC3.zip also fails. Is there any other location to manually download the map?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: ForgeMultipart-1.10.2-2.0.0.38-universal
* TolkienCraft III version: 1.1.7

## Crash report
```
[02:30:54] [MapDownload/INFO] [Mad Help]: An error occurred while downloading the map
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: java.net.ConnectException: Connection refused (Connection refused)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[02:30:54] [MapDownload/INFO] [STDERR]: [com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread:run:567]: 	at com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread.run(ContentHandler.java:555)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.Socket.connect(Socket.java:589)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.Socket.connect(Socket.java:538)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
[02:30:54] [MapDownload/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at com.brandon3055.madhelp.handlers.ContentHandler$DownloadThread.run(ContentHandler.java:552)
```

**Comment by GreatOrator** [comment]
Thank you, did not realize the link was not resolving.  Have a ticket in to my provider and will let you know as soon as they let me know it is fixed.

**Comment by GreatOrator** [comment]
Download should be fixed now.  Just tested and was able to download myself.  Let me know if you have any other issues.
